name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Dependencies
        run: |
          sudo apt-get install -y cmake
          pip install --upgrade pytest

      - name: Configure
        working-directory: ${{github.workspace}}
        run: mkdir -p build; cmake -DINSTALL_GTEST=OFF -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -S . -B build

      - name: Format and Lint Source Code
        working-directory: ${{github.workspace}}
        run: |
          clang-format-18 --dry-run -Werror src/*.cpp
          clang-tidy src/*.cpp -p ./build/compile_commands.json

      - name: Format and Lint Test Code
        working-directory: ${{github.workspace}}
        continue-on-error: true
        run: |
          clang-format-18 --dry-run -Werror test/unit_tests/*.cpp
          clang-tidy test/unit_tests/*.cpp -p ./build/compile_commands.json

      - name: Build
        working-directory: ${{github.workspace}}/build
        run: make

      - name: Run tests
        working-directory: ${{github.workspace}}/build
        run: |
          make test
